- name: Include tasks for creating directories
  import_tasks: directories.yml

- name: Copy prod.Dockerfile for production
  copy:
    src: prod.Dockerfile
    dest: /opt/jenkins/prod.Dockerfile

- name: Copy build artifacts from build node to prod node
  synchronize:
    src: /opt/build/output/jenkins.war
    dest: /opt/jenkins/jenkins.war
    mode: push
  delegate_to: "{{ groups['build-node'][0] }}"
  when: inventory_hostname in groups['prod-node']