- name: Create working directory for deployment
  file:
    path: /opt/joinfaces-example
    state: directory
    mode: '0755'

- name: Copy prod.Dockerfile for production
  copy:
    src: internal/docker/prod.Dockerfile
    dest: /opt/joinfaces-example/prod.Dockerfile

- name: Copy build artifacts from build node
  synchronize:
    src: build-node:/opt/build/output/joinfaces-example-5.4.x.war
    dest: /opt/joinfaces-example/joinfaces-example-5.4.x.war
    mode: pull
