- name: Build production Docker image
  command: docker build -t jenkins -f /opt/jenkins/prod.Dockerfile /opt/jenkins/

- name: Run application in Docker container
  docker_container:
    name: jenkins
    image: jenkins
    state: started
    ports:
      - "8080:8080"