- name: Build production Docker image
  command: docker build -t joinfaces-example.war -f /opt/joinfaces-example/prod.Dockerfile /opt/app

- name: Run application in Docker container
  docker_container:
    name: joinfaces-example
    image: joinfaces-example
    state: started
    ports:
      - "8080:8080"
