- name: Install required packages
  apt:
    name:
      - docker.io
    state: present
    update_cache: true

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
