- name: Create working directory
  file:
    path: /opt/build
    state: directory
    mode: '0755'

- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Copy build.Dockerfile for build
  copy:
    src: internal/docker/build.Dockerfile
    dest: /opt/build/build.Dockerfile

- name: Clone Jenkins repository
  git:
    repo: https://github.com/jenkinsci/jenkins.git
    dest: /opt/build/src
    version: master

- name: Build Docker image
  command: docker build -t jenkins-build -f /opt/build/build.Dockerfile /opt/build

- name: Create output directory for artifacts
  file:
    path: /opt/build/output
    state: directory
    mode: '0755'

- name: Run build container to compile the project
  command: >
    docker run --rm
    -v /opt/build/output:/war-files
    jenkins-build
