- name: Include tasks for creating directories
  import_tasks: directories.yml

- name: Clone Jenkins repository
  git:
    repo: https://github.com/jenkinsci/jenkins.git
    dest: /opt/build/src
    version: "{{ git_repo_version }}"

- name: Copy Dockerfile for build
  copy:
    src: build.Dockerfile
    dest: /opt/build/build.Dockerfile

- name: Check if Jenkins WAR file exists
  stat:
    path: /opt/build/output/jenkins.war
  register: war_file

- name: Build Docker image if WAR file does not exist
  command: docker build -t jenkins-build -f /opt/build/build.Dockerfile /opt/build/src
  when: not war_file.stat.exists

- name: Run build container to extract artifacts
  docker_container:
    name: jenkins.war-build
    image: jenkins.war-build
    state: started
    volumes:
      - /opt/build/output:/artifacts
    remove: yes
  when: not war_file.stat.exists
