- name: Create build directory
  file:
    path: /opt/build
    state: directory
    mode: '0755'

- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Clone JoinFaces repository
  git:
    repo: https://github.com/joinfaces/joinfaces-maven-war-example.git
    dest: /opt/build/src

- name: Copy Dockerfile for build
  copy:
    src: internal/docker/build.Dockerfile
    dest: /opt/build/build.Dockerfile

- name: Check if joinfaces WAR file exists
  stat:
    path: /opt/build/output/joinfaces-example-5.4.x.war
  register: war_file

- name: Build Docker image if WAR file does not exist
  command: docker build -t joinfaces-build -f /opt/build/build.Dockerfile /opt/build/src
  when: not war_file.stat.exists

- name: Create output directory for artifacts
  file:
    path: /opt/build/output
    state: directory
    mode: '0755'

- name: Run build container to extract artifacts
  command: >
    docker run --rm -v /opt/build/output:/artifacts joinfaces-build
  when: not war_file.stat.exists
