- name: Install required packages
  apt:
    name:
      - docker.io
      - git
      - python-pip
    state: present
    update_cache: true


- name: Install docker python module
  pip:
    name: docker
    state: present
    executable: pip
